export const quotes = [
    "Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me. M.Scott",
    "I'm not superstitious, but I am a little stitious. M.Scott",
    "That's what she said. M.Scott",
    "Identity theft is not a joke, Jim! Millions of families suffer every year. D.Schrute",
    "I just want to lie on the beach and eat hot dogs. K.Malone",
    "Bears. Beets. Battlestar Galactica. J.Halpert",
    "Sometimes I'll start a sentence and I don't even know where it's going. I just hope I find it along the way. M.Scott",
    "I am Beyoncé, always. M.Scott",
    "I am running away from my responsibilities. And it feels good. M.Scott",
    "I talk a lot, so I've learned to just tune myself out. K.Kapoor",
    "Sometimes the clothes at Gap Kids are too flashy, so I’m forced to go to the American Girl store and order clothes for large colonial dolls. A.Martin",
    "I declare bankruptcy! M.Scott",
    "The worst thing about prison was the dementors. M.Scott",
    "I'm an early bird and I'm a night owl. So I'm wise and I have worms. M.Scott",
    "I miss the days when there was only one party I didn't want to go to. R.Howard",

    // How I Met Your Mother Quotes
    "Legen—wait for it—dary! B.Stinson",
    "Suit up! B.Stinson",
    "Whenever I'm sad, I stop being sad and be awesome instead. B.Stinson",
    "You can't cling to the past. Because no matter how tightly you hold on, it's already gone. T.Mosby",
    "If you're not scared, you're not taking a chance, and if you're not taking a chance, then what the hell are you doing? T.Mosby",
    "Because sometimes even if you know how something's gonna end, that doesn't mean you can't enjoy the ride. T.Mosby",
    "And that, kids, is how I met your mother. T.Mosby",
    "If I ask you to change too many things about yourself, you're not gonna be the man I fell in love with. R.Scherbatsky",
    "Nothing good happens after 2:00 A.M. T.Mosby",
    "Have you met Ted? B.Stinson",
    "It’s only once you’ve stopped that you realize how hard it is to start again. T.Mosby",
    "The great moments of your life won't necessarily be the things you do; they'll also be the things that happen to you. T.Mosby",
    "Whatever you do in this life, it's not legendary unless your friends are there to see it. B.Stinson",
    "We struggle so hard to hold on to these things that we know are gonna disappear eventually. L.Aldrin",
    "Challenge accepted! B.Stinson",

    // Phil Dunphy Quotes
    "I'm the cool dad. That's my thing. I'm hip. I surf the Web. I text. LOL. P.Dunphy",
    "I've always said that if my son thinks of me as one of his idiot friends, I've succeeded as a dad. P.Dunphy",
    "The iPad comes out on my actual birthday. It's like Steve Jobs and God got together to say, 'We love you, Phil.' P.Dunphy",
    "When life gives you lemonade, make lemons. Life will be all like 'Whaaaat?!' P.Dunphy",
    "Success is 1% inspiration, 98% perspiration, and 2% attention to detail. P.Dunphy",
    "Always look people in the eye, even if they're blind. Just say 'I'm looking you in the eye, but it doesn't seem to be doing much.' P.Dunphy",
    "When in doubt, dance it out. It's scientifically proven to make everything better. P.Dunphy",
    "Watch a sunrise at least once a day. P.Dunphy",
    "If you want to be truly happy in life, surround yourself with people who make you laugh. And also, people who bring snacks. P.Dunphy",
    "I always felt bad for people with emotionally distant fathers. It turns out I'm one of them. It's a miracle I didn't end up a stripper. P.Dunphy",
    "We had no more dishes, so we were eating cereal out of a goldfish bowl. P.Dunphy"
];
